AWSTemplateFormatVersion: 2010-09-09

Description: This template creates an Application Load Balancer

Metadata:
AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Certificate ARN
        Parameters:
          - AcmCertificate
      -
        Label:
          default: Export VPC Stack Name
        Parameters:
          - EnvironmentName

Parameters:
  AcmCertificate:
    Description: The ARN of the AWS Certification Manager's Certificate
    Type: String

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:

Outputs:
